export const CREATE_GALLERY_PHOTO = "CREATE_GALLERY_PHOTO";
export const GET_GALLERY_PHOTO = "GET_GALLERY_PHOTO";
export const UPDATE_GALLERY_PHOTO = "UPDATE_GALLERY_PHOTO";
export const DELETE_GALLERY_PHOTO = "DELETE_GALLERY_PHOTO";
export const GET_ALL_GALLERY_PHOTO = "GET_ALL_GALLERY_PHOTO";
