export const CREATE_CAMERA = "CREATE_CAMERA";
export const GET_CAMERA = "GET_CAMERA";
export const UPDATE_CAMERA = "UPDATE_CAMERA";
export const DELETE_CAMERA = "DELETE_CAMERA";
export const GET_ALL_CAMERA = "GET_ALL_CAMERA";
