export const CREATE_DETAIL_CHAT = "CREATE_DETAIL_CHAT";
export const GET_DETAIL_CHAT = "GET_DETAIL_CHAT";
export const UPDATE_DETAIL_CHAT = "UPDATE_DETAIL_CHAT";
export const DELETE_DETAIL_CHAT = "DELETE_DETAIL_CHAT";
export const GET_ALL_DETAIL_CHAT = "GET_ALL_DETAIL_CHAT";
