export const CREATE_DETAIL_COMMENT = "CREATE_DETAIL_COMMENT";
export const GET_DETAIL_COMMENT = "GET_DETAIL_COMMENT";
export const UPDATE_DETAIL_COMMENT = "UPDATE_DETAIL_COMMENT";
export const DELETE_DETAIL_COMMENT = "DELETE_DETAIL_COMMENT";
export const GET_ALL_DETAIL_COMMENT = "GET_ALL_DETAIL_COMMENT";
