export const CREATE_GALLERY_VIDEO = "CREATE_GALLERY_VIDEO";
export const GET_GALLERY_VIDEO = "GET_GALLERY_VIDEO";
export const UPDATE_GALLERY_VIDEO = "UPDATE_GALLERY_VIDEO";
export const DELETE_GALLERY_VIDEO = "DELETE_GALLERY_VIDEO";
export const GET_ALL_GALLERY_VIDEO = "GET_ALL_GALLERY_VIDEO";
