export const CREATE_SOCIAL_MEDIA = "CREATE_SOCIAL_MEDIA";
export const GET_SOCIAL_MEDIA = "GET_SOCIAL_MEDIA";
export const UPDATE_SOCIAL_MEDIA = "UPDATE_SOCIAL_MEDIA";
export const DELETE_SOCIAL_MEDIA = "DELETE_SOCIAL_MEDIA";
export const GET_ALL_SOCIAL_MEDIA = "GET_ALL_SOCIAL_MEDIA";
