// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnYCrYH1woUpK0fzAaayMNnrerOuPEy-8',
    appId: '1:506839849202:web:2612c766bee9b7b9e0986b',
    messagingSenderId: '506839849202',
    projectId: 'koning-gilgamesj',
    authDomain: 'koning-gilgamesj.firebaseapp.com',
    storageBucket: 'koning-gilgamesj.appspot.com',
    measurementId: 'G-LRF6PGY3DY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcR-D0mwbJYSCeuN6IbgGLhUD_smVmyJ4',
    appId: '1:506839849202:android:23e81bd920d88f73e0986b',
    messagingSenderId: '506839849202',
    projectId: 'koning-gilgamesj',
    storageBucket: 'koning-gilgamesj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlpj_gx1Pj14fHjdUUA9JEx0WHvRBFj1U',
    appId: '1:506839849202:ios:6c4e0774598f8ca5e0986b',
    messagingSenderId: '506839849202',
    projectId: 'koning-gilgamesj',
    storageBucket: 'koning-gilgamesj.appspot.com',
    iosClientId: '506839849202-0mv1e9f22dvi57q4cksn7kfhplv35jfp.apps.googleusercontent.com',
    iosBundleId: 'com.expinc.gilgamesj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlpj_gx1Pj14fHjdUUA9JEx0WHvRBFj1U',
    appId: '1:506839849202:ios:6c4e0774598f8ca5e0986b',
    messagingSenderId: '506839849202',
    projectId: 'koning-gilgamesj',
    storageBucket: 'koning-gilgamesj.appspot.com',
    iosClientId: '506839849202-0mv1e9f22dvi57q4cksn7kfhplv35jfp.apps.googleusercontent.com',
    iosBundleId: 'com.expinc.gilgamesj',
  );
}
