name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6
  intl: ^0.18.1
  http: ^0.13.5
  bot_toast: ^4.0.4
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  audioplayers: ^4.1.0
  babylonjs_viewer: ^1.2.1
  flutter_map: ^4.0.0
  introduction_screen: ^3.1.4
  latlong2: ^0.8.2
  maps_launcher: ^2.2.0
  cached_network_image: ^3.2.3
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/audios/
    - assets/audios/tuts/
    - assets/objects/
    - assets/html/demo4/index.html
    - assets/html/demo4/itracker.js
    - assets/html/demo4/opencv.js
    - assets/html/demo4/Build/
    - assets/html/demo4/targets/
    - assets/html/demo4/TemplateData/
