part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const BLANK = _Paths.BLANK;
  static const BONUS = _Paths.BONUS;
  static const BONUS_CAMERA = _Paths.BONUS_CAMERA;
  static const BONUS_HOME = _Paths.BONUS_HOME;
  static const BROWSER = _Paths.BROWSER;
  static const BROWSER_SEARCH = _Paths.BROWSER_SEARCH;
  static const CAMERA = _Paths.CAMERA;
  static const CHAT = _Paths.CHAT;
  static const CHAT_DETAIL = _Paths.CHAT_DETAIL;
  static const CLAP = _Paths.CLAP;
  static const COMMENT = _Paths.COMMENT;
  static const CREATE_TEAM = _Paths.CREATE_TEAM;
  static const GALLERY = _Paths.GALLERY;
  static const GALLERY_IMAGE_DETAIL = _Paths.GALLERY_IMAGE_DETAIL;
  static const GALLERY_VIDEO_DETAIL = _Paths.GALLERY_VIDEO_DETAIL;
  static const INTRODUCTION = _Paths.INTRODUCTION;
  static const LOCK_MUSIC = _Paths.LOCK_MUSIC;
  static const MAP = _Paths.MAP;
  static const NEWS_DETAIL = _Paths.NEWS_DETAIL;
  static const OBJECTIVE = _Paths.OBJECTIVE;
  static const OBJECTIVE_DETAIL = _Paths.OBJECTIVE_DETAIL;
  static const PERFORMANCE = _Paths.PERFORMANCE;
  static const PHONE = _Paths.PHONE;
  static const PHONE_CALL = _Paths.PHONE_CALL;
  static const RULES = _Paths.RULES;
  static const SOCIAL_MEDIA = _Paths.SOCIAL_MEDIA;
  static const START = _Paths.START;
  static const CREATE_PLAYER = _Paths.CREATE_PLAYER;
  static const VIEW_PLAYER = _Paths.VIEW_PLAYER;
  static const INTRO = _Paths.INTRO;
  static const PRE_GAME_ITEMS = _Paths.PRE_GAME_ITEMS;
  static const PRE_GAME_TALKING_VIDEO = _Paths.PRE_GAME_TALKING_VIDEO;
  static const GO_THEATER = _Paths.GO_THEATER;
  static const CONNECTION = _Paths.CONNECTION;
  static const LIGHT = _Paths.LIGHT;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const GROUP = _Paths.GROUP;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const BLANK = '/blank';
  static const BONUS = '/bonus';
  static const BONUS_CAMERA = '/bonus-camera';
  static const BONUS_HOME = '/bonus-home';
  static const BROWSER = '/browser';
  static const BROWSER_SEARCH = '/browser-search';
  static const CAMERA = '/camera';
  static const CHAT = '/chat';
  static const CHAT_DETAIL = '/chat-detail';
  static const CLAP = '/clap';
  static const COMMENT = '/comment';
  static const CREATE_TEAM = '/create-team';
  static const GALLERY = '/gallery';
  static const GALLERY_IMAGE_DETAIL = '/gallery-image-detail';
  static const GALLERY_VIDEO_DETAIL = '/gallery-video-detail';
  static const INTRODUCTION = '/introduction';
  static const LOCK_MUSIC = '/lock-music';
  static const MAP = '/map';
  static const NEWS_DETAIL = '/news-detail';
  static const OBJECTIVE = '/objective';
  static const OBJECTIVE_DETAIL = '/objective-detail';
  static const PERFORMANCE = '/performance';
  static const PHONE = '/phone';
  static const PHONE_CALL = '/phone-call';
  static const RULES = '/rules';
  static const SOCIAL_MEDIA = '/social-media';
  static const START = '/start';
  static const CREATE_PLAYER = '/create-player';
  static const VIEW_PLAYER = '/view-player';
  static const INTRO = '/intro';
  static const PRE_GAME_ITEMS = '/pre-game-items';
  static const PRE_GAME_TALKING_VIDEO = '/pre-game-talking-video';
  static const GO_THEATER = '/go-theater';
  static const CONNECTION = '/connection';
  static const LIGHT = '/light';
  static const NOTIFICATION = '/notification';
  static const GROUP = '/group';
}
