name: app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  audioplayers: ^0.19.0
  babylonjs_viewer: ^1.2.1
  bot_toast: ^4.0.4
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_inappwebview:
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^0.14.0
  flutter_svg: ^1.1.6
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  http: ^0.13.5
  image_picker: ^1.0.4
  intl: ^0.17.0
  introduction_screen: ^3.1.4
  latlong2: ^0.8.2
  liquid_progress_indicator_v2: ^0.5.0
  maps_launcher: ^2.2.0
  network_info_plus: ^4.1.0
  noise_meter: ^4.0.1
  perfect_volume_control: ^1.0.5
  permission_handler: ^10.4.3
  qr_code_scanner: ^1.0.1
  screen_brightness: ^0.2.2+1
  shake: ^2.2.0
  torch_light: ^1.0.0
  vibration: ^1.8.1
  video_player: ^2.7.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.png'
  min_sdk_android: 21
  web:
    generate: true
    image_path: 'assets/images/logo.png'
    background_color: '#ffffff'
    theme_color: '#ffffff'
  windows:
    generate: true
    image_path: 'assets/images/logo.png'
    icon_size: 48
  macos:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/gif/
    - assets/images/
    - assets/images/maps/
    - assets/icons/
    - assets/fonts/
    - assets/audios/
    - assets/audios/tuts/
    - assets/audios/pregames/
    - assets/audios/pregames/theater_music/
    - assets/audios/pregames/night_sounds/
    - assets/objects/
    - assets/videos/
    - assets/json/
  fonts:
    - family: Centrion
      fonts:
        - asset: assets/fonts/centrion/CentrionVariable.ttf
    - family: Abel
      fonts:
        - asset: assets/fonts/abel/abel-regular.ttf
