name: "gilgamesj"
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  audioplayers: ^0.19.0
  babylonjs_viewer: ^1.1.0
  cloud_firestore: 3.1.12
  convex_bottom_bar: 3.0.0
  cupertino_icons: ^1.0.2
  drop_down_list: ^0.0.4
  firebase_auth: 3.3.14
  firebase_core: 1.14.1
  firebase_storage: 10.2.12
  flutter:
    sdk: flutter
  flutter_launch: ^0.3.0
  flutter_launcher_icons: ^0.11.0
  flutter_map: ^3.1.0
  flutter_svg: 1.0.3
  gender_picker: ^1.1.0
  geocoding: 2.0.4
  get: 4.6.1
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  image_picker: 0.8.5
  intl: 0.17.0
  introduction_screen: ^3.1.4
  latlong2: ^0.8.1
  maps_launcher: ^2.0.1
  passcode_screen: ^2.0.1
  pattern_lock: ^2.0.0
  permission_handler: ^10.2.0
  rename: ^2.0.1
  scroll_snap_list: ^0.9.1
  syncfusion_flutter_datepicker: ^20.1.51
  sqflite: ^2.2.8+4
  url_launcher: ^6.1.2
  uuid: ^3.0.7
  flutter_inappwebview:
  flutter_animation_progress_bar: ^2.3.1
  path: ^1.8.2
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_ios: "assets/images/launcher/logo.png"
  image_path_android: "assets/images/launcher/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/audios/
    - assets/audios/tuts/
    - assets/objects/
    - assets/html/demo4/index.html
    - assets/html/demo4/itracker.js
    - assets/html/demo4/opencv.js
    - assets/html/demo4/Build/
    - assets/html/demo4/targets/
    - assets/html/demo4/TemplateData/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
